### ISSUE TITLE
Feature Request: document how big integers and timestamps are

### ISSUE THREAD

**Issue by Dretch** [rescrv/HyperDex#208]
This regards the documentation at http://hyperdex.org/doc/latest/DataTypes/.

How big are integers? 32 bit? 64 bit? unrestricted? presumably they are signed?

How big are timestamps? 64 bit? What are their units? (possibly milliseconds?) What is their epoch ? (presumably the unix epoch?)

Thanks

**Comment by dandv** [comment]
:+1:

**Comment by rescrv** [comment]
Here's the documentation of the formats for the C API:  http://hyperdex.org/doc/latest/CClientAPI/#sec:api:c:client:format

Specifically, to answer your questions:
 - Integers are 64-bit signed integers (HYPERDATATYPE_INT64)
 - Timestamps are microseconds since the UNIX epoch, stored in the same format as a HyperDex integer.

If you're using the Python API, it should provide bounds checking on integers and timestamps.
