### ISSUE TITLE
depend on  some many other libs

### ISSUE THREAD

**Issue by maishi** [rescrv/HyperDex#231]
i want to use hyperdex on my project,but i find it depend on too much other libs,and it hard to install on my system.

**Comment by haoziyao** [comment]
Hi maishi,

You can try to install from source as described at http://hyperdex.org/download/

Firstly, you need to download and install all the prerequisites. Which problem you met?

**Comment by rescrv** [comment]
Most of the libraries it depends on are in-house libraries that are separate because they are used in multiple projects.  Here's a script that will install everything we built; you'll likely need to install libglog-dev and libpopt-dev first:  https://github.com/rescrv/HyperDex/blob/master/doc/install/source-install.sh
